name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Fetch master
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install dependencies
        run: npm i

      # - name: Lint
      #   run: npm run affected:lint -- --base=origin/master

      # - name: Test
      #   run: npm run affected:test -- --base=origin/master

      # - name: E2E
      #   run: npm run affected:e2e -- --base=origin/master

      - name: Build
        run: npm run build --prod

      - name: Build
        run: npm run build --prod api

      - name: Login to heroku
        uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true

      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: ${{secrets.HEROKU_STAGE_APP}}
        if: job.status == 'success'
        run: |
          rm -rf .gitignore
          mv .gitignore.heroku .gitignore
          git add -A
          git commit -m "deploy"
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku master
