name: CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Lint api
        run: npm run lint api

      - name: Test
        run: npm run test

      - name: Test api
        run: npm run test api

      - name: E2E
        run: npm run e2e
