name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run affected:lint -- --base=remotes/origin/main

      - name: Test
        run: npm run affected:test -- --base=remotes/origin/main

      - name: E2E
        run: npm run affected:e2e -- --base=remotes/origin/main

      - name: Build
        run: npm run affected:build -- --base=remotes/origin/main
